/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Rocky.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Rocky.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" position={[0, 0, 0.001]} rotation={[0, 1.571, 0]} scale={5.666}>
          <primitive object={nodes.spine005} />
          <primitive object={nodes.spine012} />
          <primitive object={nodes.Bone} />
          <group name="Cuerpo007">
            <skinnedMesh name="Cubo001" geometry={nodes.Cubo001.geometry} material={materials['Cuerpo del perrito']} skeleton={nodes.Cubo001.skeleton} />
            <skinnedMesh name="Cubo001_1" geometry={nodes.Cubo001_1.geometry} material={materials.Lenguita} skeleton={nodes.Cubo001_1.skeleton} />
            <skinnedMesh name="Cubo001_2" geometry={nodes.Cubo001_2.geometry} material={materials.Ojos} skeleton={nodes.Cubo001_2.skeleton} />
            <skinnedMesh name="Cubo001_3" geometry={nodes.Cubo001_3.geometry} material={materials['Material.001']} skeleton={nodes.Cubo001_3.skeleton} />
            <skinnedMesh name="Cubo001_4" geometry={nodes.Cubo001_4.geometry} material={materials.Trompita} skeleton={nodes.Cubo001_4.skeleton} />
            <skinnedMesh name="Cubo001_5" geometry={nodes.Cubo001_5.geometry} material={materials.Orejitas} skeleton={nodes.Cubo001_5.skeleton} />
            <skinnedMesh name="Cubo001_6" geometry={nodes.Cubo001_6.geometry} material={materials.Colita} skeleton={nodes.Cubo001_6.skeleton} />
            <skinnedMesh name="Cubo001_7" geometry={nodes.Cubo001_7.geometry} material={materials.Brillo} skeleton={nodes.Cubo001_7.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Rocky.glb')
