/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/Crate.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Crate(props) {
  const { nodes, materials } = useGLTF('/models/Crate.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={39.086}>
        <mesh geometry={nodes.Crate_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Crate_2.geometry} material={materials.Wood_Light} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Crate.glb')
