/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/farmStage.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FarmStage(props) {
  const { nodes, materials } = useGLTF('/models/farmStage.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.679, -6.454, -18.501]} rotation={[-Math.PI / 2, 0, -1.584]} scale={0.445}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Silo3} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Tractor3} position={[-12.766, -0.175, 0]} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Fences} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Barn3} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Tractor4} position={[-12.766, -0.175, 0]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Scarecrow2} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Ground2} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Windmill} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Scarec3} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Ground} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.HayBale2} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Silo5} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Tractor2} position={[-12.766, -0.175, 0]} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.HayBale} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Barn2} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Hen4} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Corn1} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Cow1.001']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Barn} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Pine} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Hen3} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Cow3} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Cow3} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Trunk} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Green} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Hen2} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Gray} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Corn2} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Hen_2} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Cow1} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Cow2} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Tractor} position={[-12.766, -0.175, 0]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Windmill2} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.LightB} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Corn3} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Black} />
      </group>
      <mesh geometry={nodes.Object_37001.geometry} material={materials['Green.001']} position={[0.387, 1.284, -0.526]} rotation={[-Math.PI / 2, 0, -1.584]} scale={0.048} />
      <mesh geometry={nodes.footing.geometry} material={materials['Material.036']} position={[0.068, -0.049, -2.295]} scale={5.061} />
      <mesh geometry={nodes.footing_02.geometry} material={materials['Material.037']} position={[0.068, 0.429, -2.295]} scale={4.923} />
    </group>
  )
}

useGLTF.preload('/models/farmStage.glb')
